# MariaDB ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: maria-configmap
  namespace: db
  labels:
    id: "19108294"
    app: maria
    env: dev
data:
  MYSQL_DATABASE: "wordpress"
  MYSQL_USER: "wordpress"
---
# MariaDB Secret
apiVersion: v1
kind: Secret
metadata:
  name: maria-secret
  namespace: db
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: d29yZHByZXNz  # 'wordpress' in base64
  MYSQL_PASSWORD: d29yZHByZXNz       # 'wordpress' in base64
---
# MariaDB Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deploayment
  namespace: db
  labels:
    id: "19108294"
    app: maria
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maria
  template:
    metadata:
      labels:
        id: "19108294"
        app: maria
        env: dev
        version: "1.0.0"
    spec:
      containers:
      - name: maria
        image: mariadb:10.6.4-focal
        envFrom:
          - configMapRef:
              name: maria-configmap
          - secretRef:
              name: maria-secret
        ports:
        - containerPort: 3306
---
# MariaDB Service
apiVersion: v1
kind: Service
metadata:
  name: maria
  namespace: db
spec:
  selector:
    id: "19108294"
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
