apiVersion: v1
kind: Secret
metadata:
    name: wp-secret
    namespace: wp
type: Opaque
data:
    WORDPRESS_DB_PASSWORD: ENC[AES256_GCM,data:blahJ2N9hFRXaiI/,iv:xH48Bxpo0WoTSRAbh5OwpdcTPcpam5UEX8uY+LS4qTc=,tag:juWqLx3BbEV8Ka4uryzXkQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/buoyant-climate-434700-s9/locations/northamerica-northeast1/keyRings/my-keyring/cryptoKeys/newkey
          created_at: "2024-11-17T03:26:40Z"
          enc: CiQAN+aNJBc7s4/iaqXypaYcQE1LTaXv9QaAaH+/jOskuS6TwXYSSQAofo7fdYMeEuNIjv29pleer9lnku02Ar3pXD/ebiuQKirRWtho1Atky26GzFpXfIKbF+2J3c0V4gBeLOviY7TFZfNgGKUgr+w=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-11-17T03:26:40Z"
    mac: ENC[AES256_GCM,data:wqGJx6MI7Pc4+zybg1a7foN12LJIs2qzacCvOYxfoyVbvlsIjcMHosqWoFoT5Ds4nqc4PBnMohVSCay+vSc3vpifbrHca20X3Xm3aFCuUIKOkDvzPI/NuoFmVbVi1YFxxEdFUtaTz7ZNE2lhaG3cIZlgEi7bpMYlVta2s2IVEwg=,iv:VYrNLizLJkBACQwL/aGdTBvGn887cw3pd4CpJXVUKB8=,tag:cr0kp3eocaBvPy2jlUJcmg==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.1
